# Generated by Django 3.0.2 on 2020-01-30 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillingDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipmentId', models.IntegerField(max_length=30)),
                ('salutationCode', models.IntegerField(max_length=10)),
                ('firstName', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('streetName', models.CharField(max_length=50)),
                ('houseNumber', models.IntegerField(max_length=10)),
                ('houseNumberExtended', models.CharField(max_length=5, null=True)),
                ('addressSupplement', models.CharField(max_length=50, null=True)),
                ('extraAddressInformation', models.CharField(max_length=50, null=True)),
                ('zipCode', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=30)),
                ('countryCode', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50, null=True)),
                ('vatNumber', models.CharField(max_length=50, null=True)),
                ('chamberOfCommerceNumber', models.IntegerField(max_length=30, null=True)),
                ('orderReference', models.CharField(max_length=50, null=True)),
                ('deliveryPhoneNumber', models.IntegerField(max_length=17, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipmentId', models.IntegerField(max_length=30)),
                ('salutationCode', models.IntegerField(max_length=10)),
                ('firstName', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('streetName', models.CharField(max_length=50)),
                ('houseNumber', models.IntegerField(max_length=10)),
                ('houseNumberExtended', models.CharField(max_length=5, null=True)),
                ('addressSupplement', models.CharField(max_length=50, null=True)),
                ('extraAddressInformation', models.CharField(max_length=50, null=True)),
                ('zipCode', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=30)),
                ('countryCode', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50, null=True)),
                ('vatNumber', models.CharField(max_length=50, null=True)),
                ('chamberOfCommerceNumber', models.IntegerField(max_length=30, null=True)),
                ('orderReference', models.CharField(max_length=50, null=True)),
                ('deliveryPhoneNumber', models.IntegerField(max_length=17, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipmentId', models.IntegerField(max_length=30)),
                ('orderItemId', models.IntegerField(max_length=30)),
                ('orderId', models.IntegerField(max_length=30)),
                ('orderDate', models.DateTimeField(max_length=35)),
                ('latestDeliveryDate', models.DateTimeField(max_length=35)),
                ('ean', models.IntegerField(max_length=20)),
                ('title', models.CharField(max_length=250)),
                ('quantity', models.IntegerField(max_length=10)),
                ('offerPrice', models.FloatField(max_length=20)),
                ('offerCondition', models.CharField(max_length=10)),
                ('offerReference', models.CharField(max_length=30, null=True)),
                ('fulfilmentMethod', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Shipments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipmentId', models.IntegerField(max_length=30, unique=True)),
                ('shipmentDate', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemParamaters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loginHostURL', models.CharField(max_length=100, null=True)),
                ('clientID', models.CharField(max_length=200, null=True)),
                ('clientSecret', models.CharField(max_length=200, null=True)),
                ('apiHostURL', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipmentId', models.IntegerField(max_length=30)),
                ('transportId', models.IntegerField(max_length=30)),
                ('transporterCode', models.CharField(max_length=10)),
                ('trackAndTrace', models.CharField(max_length=30)),
                ('shippingLabelId', models.IntegerField(max_length=30, null=True)),
                ('shippingLabelCode', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
